# Generated by Django 3.2.5 on 2021-07-25 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_remove_superplayer_addby'),
    ]

    operations = [
        migrations.AddField(
            model_name='superplayer',
            name='addBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
